# Use root/password as user/password credentials
version: '3'

services:

  mysqldb:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - ./mysqldata:/var/lib/mysql    
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: newsonwire


  newsonwire:
    image: newsonwire
    
    # Original command by Luigi
    #command: ["java","-jar","-Xms24g","-Xmx50g","-Dlogs=/app/logs","-Dcli=true","-Dforce-crawling=false","pages-classification-alpha-0.1-jar-with-dependencies.jar"]
    
    # CRAWLING mode command (comment to disable crawling mode startup):
    command: dockerize -wait tcp://mysqldb:3306 -timeout 3m java -jar -Dlogs=/app/logs -Dcli=false -Dforce-crawling=true pages-classification-alpha-0.1-jar-with-dependencies.jar    
    
    # CLASSIFICATION mode command (comment to disable classification mode startup):
    #command: dockerize -wait tcp://mysqldb:3306 -timeout 3m java -jar -Dlogs=/app/logs -Dcli=true -Dforce-crawling=false pages-classification-alpha-0.1-jar-with-dependencies.jar 
    
    volumes:
     - ./app/config:/app/config
     - ./app/data:/app/data
     - ./app/goldens:/app/goldens
     - ./app/debug:/app/debug
     - ./app/csv:/app/csv
     - ./app/results:/app/results
    depends_on:
     - mysqldb
     - adminer
    ports:
     - 4040:4040
    
  
  adminer:
    image: adminer    
    depends_on:
     - mysqldb
    ports:
      - 8080:8080
    

