# Use root/example as user/password credentials
version: '3'

services:

  mysqldb:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - ./mysqldata:/var/lib/mysql    
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: newsonwire


  newsonwire:
    image: newsonwire
    # Sovrascrive il comando di default (-Xms, -Xmx rimossi)
    command: ["java", "-jar", "-Dlogs=/app/logs", "-Dcli=true", "-Dforce-crawling=false", "pages-classification-alpha-0.1-jar-with-dependencies.jar"]
    volumes:
     - ./app/config:/app/config
     - ./app/data:/app/data
     - ./app/goldens:/app/goldens
     - ./app/debug:/app/debug
     - ./app/csv:/app/csv
     - ./app/results:/app/results
    depends_on:
     - mysqldb
    ports:
     - 4040:4040
    
  
  adminer:
    image: adminer    
    depends_on:
     - mysqldb
    ports:
      - 8080:8080
    

